# Generated by Django 4.1.7 on 2023-06-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("My_Portfolio", "0002_delete_about_me"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.FileField(null=True, upload_to="")),
                ("description", models.TextField(null=True)),
            ],
        ),
    ]
