# Generated by Django 4.1.7 on 2023-06-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("My_Portfolio", "0003_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("img", models.FileField(null=True, upload_to="")),
                ("description", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Testimonials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("img", models.FileField(null=True, upload_to="")),
                ("mssg", models.TextField(null=True)),
            ],
        ),
    ]
