# Generated by Django 4.1.7 on 2023-06-21 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("My_Portfolio", "0004_review_testimonials"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Testimonials",
        ),
    ]
