# Generated by Django 4.1.7 on 2023-06-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("My_Portfolio", "0005_delete_testimonials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="type",
            field=models.CharField(
                choices=[["video", "video"], ["images", "images"], ["gif", "gif"]],
                max_length=100,
                null=True,
            ),
        ),
    ]
