# Generated by Django 4.1.7 on 2023-06-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("My_Portfolio", "0006_alter_work_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="video",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
