# Generated by Django 4.1.7 on 2023-06-22 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("My_Portfolio", "0007_work_video"),
    ]

    operations = [
        migrations.RenameField(
            model_name="work",
            old_name="img1",
            new_name="gif",
        ),
        migrations.RenameField(
            model_name="work",
            old_name="img2",
            new_name="img",
        ),
        migrations.RemoveField(
            model_name="work",
            name="img3",
        ),
    ]
