# Generated by Django 4.1.7 on 2023-02-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Category",
                    models.CharField(
                        choices=[
                            ["Commercial", "Commercial"],
                            ["Personal", "Personal"],
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=100, null=True)),
                ("img1", models.FileField(null=True, upload_to="")),
                ("img2", models.FileField(null=True, upload_to="")),
                ("img3", models.FileField(null=True, upload_to="")),
                ("img4", models.FileField(null=True, upload_to="")),
                ("img5", models.FileField(null=True, upload_to="")),
                ("short_description", models.TextField(null=True)),
                ("long_description", models.TextField(null=True)),
            ],
        ),
    ]
