# Generated by Django 4.1.7 on 2023-03-02 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("My_portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, null=True)),
                ("img", models.FileField(null=True, upload_to="")),
                ("short_description", models.TextField(null=True)),
                ("long_description", models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="work",
            name="img1",
        ),
        migrations.RemoveField(
            model_name="work",
            name="img2",
        ),
        migrations.RemoveField(
            model_name="work",
            name="img3",
        ),
        migrations.RemoveField(
            model_name="work",
            name="img4",
        ),
        migrations.RemoveField(
            model_name="work",
            name="img5",
        ),
        migrations.CreateModel(
            name="Work_related_image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img1", models.FileField(null=True, upload_to="")),
                ("img2", models.FileField(null=True, upload_to="")),
                ("img3", models.FileField(null=True, upload_to="")),
                (
                    "workdata",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="My_portfolio.work",
                    ),
                ),
            ],
        ),
    ]
