# Generated by Django 4.1.7 on 2023-03-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("My_portfolio", "0002_blog_remove_work_img1_remove_work_img2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="img1",
            field=models.FileField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="work",
            name="img2",
            field=models.FileField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="work",
            name="img3",
            field=models.FileField(null=True, upload_to=""),
        ),
        migrations.DeleteModel(
            name="Work_related_image",
        ),
    ]
